#!/bin/bash



script=${BASH_SOURCE[0]}

src=${script%/*}

export src

# echo $src

# export PATH=$PATH:$src

# echo $PATH

cd $src/..

[ ! -d "./databases" ] && mkdir ./databases

cd scripts

pwd

select choice in "1: Show available databases" "2: Create new database" "3: Rename a database" "4: Use a database" "5: Drop a database" "6: Disconnect from engine"	
do
		case $choice in "1: Show available databases")
			echo "you chose 1"
			;;
				"2: Create new database")
			./create.database
			;;
				"3: Rename a database")
			echo "you chose 3"
			;;
				"4: Use a database")
			echo "you chose 4"
			;;
				"5: Drop a database")
			echo "you chose 5"
			;;
				"6: Disconnect from engine")
			echo "You have disconnected from databases"
			exit
			;;
		esac
done
