#!/bin/bash

cd ..

[ ! -d "./databases" ] && mkdir ./databases

cd scripts

select choice in "Show available databases" "Create new database" "Rename a database" "Use a database" "Drop a database" "Disconnect from engine"	
do
		case $choice in 

				"Show available databases")
			./show.databases
			;;
				"Create new database")
			./create.database
			;;
				"Rename a database")
			./rename.database
			;;
				"Use a database")
			./use.database
			;;
				"Drop a database")
			./drop.database
			;;
				"Disconnect from engine")
			echo "You have disconnected from databases"
			exit
			;;
		esac
done
